При проверке локально (запуск python server.py из директории с файлами):
http://localhost:8080/ - начальная страница
http://localhost:8080/success - страница успешного запуска
http://localhost:8080/fail - страница с ошибкой

При проверке с сервера heroku:
https://fierce-badlands-01919.herokuapp.com/ - начальная страница
https://fierce-badlands-01919.herokuapp.com/success - страница успешного запуска
https://fierce-badlands-01919.herokuapp.com/fail - страница с ошибкой

В файле config.py нужно ввести свой реальный адрес для Sentry.




 